[package]
name = "tg-design"
edition.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
tg-shared.workspace = true
tg-armor.workspace = true
tg-weapon.workspace = true
tg-ballistics.workspace = true
tg-penetration.workspace = true
tg-damage.workspace = true
tg-replay.workspace = true
tg-vehicle.workspace = true
tg-physics.workspace = true
